trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.11.13'
      - task: TerraformCLI@0
        displayName: Init
        inputs:
          command: 'init'
      - task: TerraformCLI@0
        displayName: Validate
        inputs:
          command: 'validate'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(System.DefaultWorkingDirectory)'
          artifactName: drop

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: RunIt
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'sandbox'
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            - task: TerraformInstaller@0
              inputs:
                terraformVersion: '0.11.13'
            - task: TerraformCLI@0
              displayName: Validate
              inputs:
                command: 'validate'
